# Generated by Django 5.2.1 on 2025-05-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrailSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('gps', models.CharField(blank=True, max_length=100)),
                ('start_end', models.CharField(blank=True, max_length=200)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('elevation', models.PositiveIntegerField()),
                ('difficulty', models.CharField(max_length=50)),
                ('trail_type', models.CharField(max_length=50)),
                ('estimated_time', models.DecimalField(decimal_places=1, max_digits=4)),
                ('conditions', models.TextField(blank=True)),
                ('accessibility', models.TextField(blank=True)),
                ('hiker_biker', models.CharField(max_length=50)),
                ('completed_as', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='trail_photos/')),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
